Repository hansei-hanum/hanum-frontend, pull requests merged in 2023-09, with the labels that each got.

#32 feat: add calendar screen
  android/.gradle/8.0.1/checksums/checksums.lock
  android/.gradle/8.0.1/checksums/md5-checksums.bin
  android/.gradle/8.0.1/checksums/sha1-checksums.bin
  android/.gradle/8.0.1/fileHashes/fileHashes.bin
  android/.gradle/8.0.1/fileHashes/fileHashes.lock
  ios/Podfile.lock
  ios/build/generated/ios/FBReactNativeSpecJSI-generated.cpp
  ios/build/generated/ios/FBReactNativeSpecJSI.h
  ios/build/generated/ios/React-Codegen.podspec.json
  metro.config.js
  package.json
  src/Router.tsx
  src/components/auth/AuthForm/styled.ts
  src/components/common/ContentBox/index.tsx
  src/components/common/Text/index.tsx
  src/components/home/Calendar/index.tsx
  src/constants/calendar.ts
  src/constants/index.ts
  src/screens/auth/main/styled.ts
  src/screens/auth/verifyCode/index.tsx
  src/screens/calendar/index.tsx
  src/screens/calendar/styled.ts
  src/screens/hanumPay/styled.ts
  src/screens/home/index.tsx
  src/screens/home/styled.ts
  src/screens/index.ts
  src/screens/lunchTable/styled.ts
  src/screens/schedule/styled.ts
  yarn.lock
Labels: ✨ 기능, 🎨 디자인

#34 bug: android lunch table screen header broken
  android/.gradle/8.0.1/executionHistory/executionHistory.lock
  android/.gradle/8.0.1/fileHashes/fileHashes.bin
  android/.gradle/8.0.1/fileHashes/fileHashes.lock
  android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/components/home/Header/index.tsx
  src/components/home/Header/styled.ts
  src/components/home/index.ts
  src/components/index.ts
  src/components/lunchTable/Header/index.tsx
  src/components/lunchTable/Header/styled.ts
  src/components/lunchTable/index.ts
  src/screens/home/index.tsx
  src/screens/home/styled.ts
  src/screens/lunchTable/index.tsx
  src/screens/lunchTable/styled.ts
Labels: 🎨 디자인, 🐛 버그

#36 bug: several style issue
  .eslintcache
  .vscode/settings.json
  android/.gradle/8.0.1/executionHistory/executionHistory.lock
  android/.gradle/8.0.1/fileHashes/fileHashes.bin
  android/.gradle/8.0.1/fileHashes/fileHashes.lock
  android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  ios/Hanum/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/build/generated/ios/React-Codegen.podspec.json
  src/components/auth/AuthForm/index.tsx
  src/components/auth/AuthForm/styled.ts
  src/components/auth/TextFieldForm/index.tsx
  src/components/common/Icon/index.tsx
  src/components/common/Icon/styled.ts
  src/components/common/Text/index.tsx
  src/components/home/Header/styled.ts
  src/components/lunchTable/Header/styled.ts
  src/components/schedule/ClassList/index.tsx
  src/components/schedule/ClassList/styled.ts
  src/components/schedule/WeekDay/styled.ts
  src/screens/auth/main/index.tsx
  src/screens/auth/main/styled.ts
  src/screens/auth/verifyCode/index.tsx
  src/screens/calendar/index.tsx
  src/screens/calendar/styled.ts
  src/screens/home/index.tsx
  src/screens/lunchTable/index.tsx
  src/screens/main/index.tsx
  src/screens/schedule/index.tsx
  src/screens/schedule/styled.ts
  src/screens/showMore/index.tsx
  src/utils/checkSize.ts
  src/utils/index.ts
  src/utils/responsiveSize.ts
Labels: 🎨 디자인, 🐛 버그

#39 feat: add get user profile
  assets/icons/calendar.svg
  assets/icons/index.ts
  assets/icons/lunchTable.svg
  assets/icons/party.svg
  assets/icons/pay.svg
  assets/icons/schedule.svg
  assets/icons/showMore.svg
  assets/icons/timer.svg
  assets/images/user.png
  src/Router.tsx
  src/components/common/Icon/styled.ts
  src/components/home/AlertBox/index.tsx
  src/components/home/Calendar/index.tsx
  src/components/home/Content/index.tsx
  src/components/home/HanumPay/index.tsx
  src/components/home/LunchTable/index.tsx
  src/components/home/Timer/index.tsx
  src/constants/headerIconStyle.tsx
  src/constants/index.ts
  src/constants/showMore.ts
  src/screens/calendar/styled.ts
  src/screens/home/index.tsx
  src/screens/lunchTable/index.tsx
  src/screens/schedule/index.tsx
  src/screens/showMore/index.tsx
  src/screens/showMore/styled.ts
Labels: ✨ 기능, 🎨 디자인

#43 feat: add user info screen
  android/.gradle/8.0.1/executionHistory/executionHistory.lock
  android/.gradle/8.0.1/fileHashes/fileHashes.bin
  android/.gradle/8.0.1/fileHashes/fileHashes.lock
  android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/Router.tsx
  src/api/api.tsx
  src/components/auth/AuthForm/styled.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/styled.ts
  src/components/common/Icon/styled.ts
  src/components/home/Calendar/index.tsx
  src/components/home/Content/index.tsx
  src/components/home/HanumPay/index.tsx
  src/components/home/Header/index.tsx
  src/components/home/LunchTable/styled.ts
  src/components/index.ts
  src/components/lunchTable/Header/index.tsx
  src/components/lunchTable/Header/styled.ts
  src/components/userInfo/InfoBox/index.tsx
  src/components/userInfo/InfoBox/styled.ts
  src/components/userInfo/index.ts
  src/constants/showMore.ts
  src/hooks/query/useAuth/index.tsx
  src/hooks/query/useStudentCodeVerify/index.tsx
  src/screens/auth/main/index.tsx
  src/screens/auth/studentVerify/index.tsx
  src/screens/calendar/index.tsx
  src/screens/home/index.tsx
  src/screens/index.ts
  src/screens/lunchTable/index.tsx
  src/screens/showMore/index.tsx
  src/screens/showMore/styled.ts
  src/screens/userInfo/index.tsx
  src/screens/userInfo/styled.ts
  src/utils/checkOs.ts
  src/utils/checkSize.ts
  src/utils/formattedDepartment.ts
  src/utils/index.ts
  src/utils/responsiveSize.ts
Labels: ✨ 기능, 🎨 디자인

#46 feat: add member secession modal add logout
  .eslintcache
  android/.gradle/8.0.1/checksums/checksums.lock
  android/.gradle/8.0.1/checksums/md5-checksums.bin
  android/.gradle/8.0.1/checksums/sha1-checksums.bin
  android/.gradle/8.0.1/executionHistory/executionHistory.lock
  android/.gradle/8.0.1/fileHashes/fileHashes.bin
  android/.gradle/8.0.1/fileHashes/fileHashes.lock
  android/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  assets/icons/index.ts
  assets/icons/mealIcon.svg
  assets/icons/schedule.svg
  assets/icons/timerIcon.svg
  ios/Podfile.lock
  package.json
  src/Router.tsx
  src/components/auth/AuthForm/styled.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/styled.ts
  src/components/common/Icon/styled.ts
  src/components/home/Content/index.tsx
  src/components/home/LunchTable/index.tsx
  src/components/home/Timer/index.tsx
  src/screens/home/index.tsx
  src/screens/home/styled.ts
  src/screens/index.ts
  src/screens/lunchTable/index.tsx
  src/screens/schedule/index.tsx
  src/screens/userInfo/index.tsx
  src/screens/userInfo/styled.ts
  src/screens/webView/index.tsx
  src/screens/webView/styled.ts
  yarn.lock
Labels: ✨ 기능, 🎨 디자인

#51 bug: interface issue on android
  App.tsx
  ios/Hanum/Info.plist
  src/Router.tsx
  src/api/auth.ts
  src/assets/lottie/failed.json
  src/assets/lottie/success.json
  src/components/auth/AuthForm/styled.ts
  src/components/auth/TextFieldForm/index.tsx
  src/components/auth/TextFieldForm/styled.ts
  src/constants/boxShadow.ts
  src/screens/showMore/index.tsx
  tsconfig.json
Labels: 🎨 디자인, 🐛 버그

#52 [FEATURE] FCM 연동, 안드로이드 패키지명 변경
  App.tsx
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/debug/java/com/hanowl/hanum/ReactNativeFlipper.java
  android/app/src/main/java/com/hanowl/hanum/MainActivity.java
  android/app/src/main/java/com/hanowl/hanum/MainApplication.java
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  ios/GoogleService-Info.plist
  ios/Hanum.xcodeproj/project.pbxproj
  ios/Hanum/AppDelegate.mm
  ios/Hanum/Hanum.entitlements
  ios/Hanum/Info.plist
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/screens/auth/main/index.tsx
Labels: ✨ 기능

#62 feat: hanum pay backend connection
  App.tsx
  src/Router.tsx
  src/api/api.tsx
  src/api/auth.ts
  src/api/index.ts
  src/api/pay.ts
  src/atoms/booth.ts
  src/atoms/index.ts
  src/components/auth/AuthForm/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/styled.ts
  src/components/common/Modal/styled.ts
  src/components/common/Text/index.tsx
  src/components/hanumPay/QRScanner/index.tsx
  src/components/hanumPay/QRScannerBox/index.tsx
  src/components/hanumPay/QRScannerBox/styled.ts
  src/components/hanumPay/index.ts
  src/components/home/HanumPay/index.tsx
  src/hooks/query/index.ts
  src/hooks/query/useFetchUser/index.tsx
  src/hooks/query/useGetPayDetail/index.tsx
  src/hooks/query/useGetPaymentAmount/index.tsx
  src/hooks/query/usePayment/index.tsx
  src/hooks/usePressingAnimation.ts
  src/screens/auth/main/index.tsx
  src/screens/hanumPay/index.ts
  src/screens/hanumPay/main/index.tsx
  src/screens/hanumPay/main/styled.ts
  src/screens/hanumPay/pay/index.tsx
  src/screens/hanumPay/pay/styled.ts
  src/screens/hanumPay/qr/index.tsx
  src/screens/hanumPay/qr/styled.ts
  src/screens/hanumPay/status/styled.ts
  src/screens/home/index.tsx
  src/screens/userInfo/index.tsx
  src/utils/formattedMoney.ts
Labels: ✨ 기능, 🎨 디자인, 🐛 버그

#63 bug: android multiple unexpected behavior
  src/components/common/Button/index.tsx
  src/components/home/HanumPay/index.tsx
  src/screens/hanumPay/main/index.tsx
  src/screens/hanumPay/main/styled.ts
  src/screens/hanumPay/qr/index.tsx
  src/screens/schedule/index.tsx
Labels: ✨ 기능, 🐛 버그

#65 feat: fcm server synchronization linking
  .eslintcache
  ios/Hanum/AppDelegate.mm
  ios/Hanum/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/Hanum/Images.xcassets/Contents.json
  ios/Hanum/Images.xcassets/LaunchImage.imageset/Contents.json
  package.json
  src/Router.tsx
  src/api/api.tsx
  src/api/auth.ts
  src/api/index.ts
  src/api/notification.ts
  src/hooks/index.ts
  src/hooks/query/auth/index.ts
  src/hooks/query/auth/useAuth/index.tsx
  src/hooks/query/auth/useFetchUser/index.tsx
  src/hooks/query/auth/usePhone/index.tsx
  src/hooks/query/auth/useStudentCodeVerify/index.tsx
  src/hooks/query/index.ts
  src/hooks/query/notification/index.ts
  src/hooks/query/notification/useConnectNotification/index.tsx
  src/hooks/query/pay/index.ts
  src/hooks/query/pay/useGetPayDetail/index.tsx
  src/hooks/query/pay/useGetPaymentAmount/index.tsx
  src/hooks/query/pay/usePayment/index.tsx
  src/hooks/useInitNavigate.tsx
  src/screens/auth/main/index.tsx
  src/screens/auth/main/styled.ts
  src/screens/auth/studentVerify/index.tsx
  src/screens/auth/studentVerify/styled.ts
  src/screens/hanumPay/qr/index.tsx
  src/screens/hanumPay/status/index.tsx
  src/screens/hanumPay/status/styled.ts
  src/screens/home/index.tsx
  src/screens/userInfo/index.tsx
Labels: ✨ 기능, 🐛 버그

#66 feat: add teacher verify screen
  src/Router.tsx
  src/screens/auth/index.ts
  src/screens/auth/main/index.tsx
  src/screens/auth/teacherVerify/index.tsx
  src/screens/auth/teacherVerify/styled.ts
Labels: ✨ 기능

#68 feat: add get school schedule
  package.json
  src/api/api.tsx
  src/api/auth.ts
  src/api/info.ts
  src/api/notification.ts
  src/components/common/Modal/index.tsx
  src/components/hanumPay/QRScanner/index.tsx
  src/components/hanumPay/QRScannerBox/index.tsx
  src/components/home/Calendar/index.tsx
  src/components/schedule/ClassList/index.tsx
  src/components/schedule/ClassList/styled.ts
  src/constants/calendar.ts
  src/constants/index.ts
  src/hooks/query/auth/useAuth/index.tsx
  src/hooks/query/auth/useFetchUser/index.tsx
  src/hooks/query/auth/useStudentCodeVerify/index.tsx
  src/hooks/query/index.ts
  src/hooks/query/info/index.ts
  src/hooks/query/info/useGetMonthSchedule/index.tsx
  src/hooks/query/info/useGetSchedule/index.tsx
  src/hooks/query/info/useGetTimeTable/index.tsx
  src/screens/auth/main/index.tsx
  src/screens/auth/main/styled.ts
  src/screens/auth/studentVerify/index.tsx
  src/screens/auth/teacherVerify/index.tsx
  src/screens/calendar/index.tsx
  src/screens/hanumPay/qr/index.tsx
  src/screens/home/index.tsx
  src/screens/schedule/index.tsx
  src/screens/schedule/styled.ts
  src/screens/userInfo/index.tsx
Labels: ✨ 기능, 🎨 디자인
