Repository hansei-hanum/hanum-frontend, pull requests merged in 2024-02, with the labels that each got.

#99 feat: add toastify
  App.tsx
  ios/Podfile
  package.json
  src/Router.tsx
  src/components/common/ToastLayout/index.tsx
  src/components/common/ToastLayout/styled.ts
  src/components/common/index.ts
  src/components/home/Schedule/index.tsx
  src/components/mealTable/MealTableLayout/index.tsx
  src/components/showMore/ShowMoreHeader/index.tsx
  src/constants/index.ts
  src/constants/toast.tsx
  src/screens/community/main/index.tsx
  src/screens/community/postDetail/index.tsx
  src/screens/home/index.tsx
Labels: ✨ 기능, 🎨 디자인

#101 feat: 100 add version update modal
  package.json
  src/Router.tsx
  src/components/auth/AuthModal/index.tsx
  src/components/common/CheckVersion/index.tsx
  src/components/common/index.ts
  src/hooks/useCodePush.tsx
  src/screens/community/postDetail/index.tsx
  src/screens/community/postDetail/styled.ts
  src/screens/home/index.tsx
Labels: ✨ 기능, 🎨 디자인

#103 feat: add haptic
  package.json
  src/Router.tsx
  src/api/auth.ts
  src/api/notification.ts
  src/hooks/useNavigate.tsx
  src/screens/community/main/index.tsx
  src/screens/main/index.tsx
  src/styles/index.ts
  src/styles/tabBar.ts
Labels: ♻️ 리팩토링, ✨ 기능, 🎨 디자인

#105 feat: change authentication UI
  src/Router.tsx
  src/api/auth.ts
  src/api/notification.ts
  src/components/auth/AuthInputForm/index.tsx
  src/components/auth/AuthInputForm/styled.ts
  src/components/auth/AuthLayout/index.tsx
  src/components/auth/AuthModal/index.tsx
  src/components/common/GoBackHeader/index.tsx
  src/hooks/index.ts
  src/hooks/useAuthInput.tsx
  src/hooks/useOpacityAnimation.tsx
  src/screens/auth/form/index.tsx
  src/screens/auth/form/styled.ts
  src/screens/auth/index.ts
  src/screens/auth/main/index.tsx
  src/screens/auth/name/index.tsx
  src/screens/auth/phone/index.tsx
  src/utils/checkType.ts
Labels: ✨ 기능, 🎨 디자인

#108 feat: add hanowl apply form
  src/Router.tsx
  src/atoms/hanowlApply.ts
  src/atoms/index.ts
  src/components/auth/AuthLayout/index.tsx
  src/components/auth/index.ts
  src/components/common/GoBackHeader/index.tsx
  src/components/common/NoScrollbarScrollView/index.tsx
  src/components/common/SelectBox/index.tsx
  src/components/common/SelectBox/styled.ts
  src/components/common/index.ts
  src/components/eoullim/box/index.tsx
  src/components/eoullim/index.ts
  src/components/eoullim/vote/index.tsx
  src/components/hanowlApply/ApplyInput/index.tsx
  src/components/hanowlApply/ApplyInput/styled.ts
  src/components/hanowlApply/ConfirmBox/index.tsx
  src/components/hanowlApply/ConfirmBox/styled.ts
  src/components/hanowlApply/index.ts
  src/components/home/Content/index.tsx
  src/components/index.ts
  src/components/layouts/AppLayout/index.tsx
  src/components/layouts/AppLayout/styled.ts
  src/components/layouts/AppLayoutWithoutButton/index.tsx
  src/components/layouts/AppLayoutWithoutButton/styled.ts
  src/components/layouts/SelectLayout/index.tsx
  src/components/layouts/SelectLayout/styled.ts
  src/components/layouts/ToastLayout/index.tsx
  src/components/layouts/ToastLayout/styled.ts
  src/components/layouts/index.ts
  src/constants/common/boxShadow.ts
  src/constants/common/index.ts
  src/constants/common/regex.ts
  src/constants/common/screen.ts
  src/constants/hanowlApply.ts
  src/constants/index.ts
  src/screens/auth/form/index.tsx
  src/screens/auth/verify/index.tsx
  src/screens/auth/verifyCode/index.tsx
  src/screens/community/createPost/index.tsx
  src/screens/community/createPost/styled.ts
  src/screens/hanowlApply/applyContents/index.tsx
  src/screens/hanowlApply/confirm/index.tsx
  src/screens/hanowlApply/confirm/styled.ts
  src/screens/hanowlApply/finalConfirm/index.tsx
  src/screens/hanowlApply/finalConfirm/styled.ts
  src/screens/hanowlApply/index.ts
  src/screens/hanowlApply/selectTeam/index.tsx
  src/screens/hanumPay/pay/index.tsx
  src/screens/index.ts
  src/screens/main/index.tsx
  src/screens/schedule/index.tsx
  src/screens/showMore/index.tsx
  src/screens/timeTable/index.tsx
  src/styles/styled.d.ts
  src/styles/tabBar.ts
  src/styles/theme.ts
Labels: ♻️ 리팩토링, ✨ 기능, 🎨 디자인

#106 feat: add time-table-tab
  package.json
  src/components/home/TimeTableTab/index.tsx
  src/components/home/TimeTableTab/styled.ts
  src/components/home/index.ts
  src/components/timeTable/List/index.tsx
  src/constants/timTableData.ts
  src/screens/home/index.tsx
  src/screens/main/index.tsx
Labels: ✨ 기능, 🎨 디자인, 🐛 버그

#113 feat: add lunch time and brake time
  src/Router.tsx
  src/components/home/TimeTableTab/index.tsx
  src/components/home/TimeTableTab/styled.ts
Labels: ✨ 기능

#114 feat connect hanowl site
  android/build.gradle
  package.json
  src/Router.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/BottomSheet/styled.ts
  src/components/common/Button/index.tsx
  src/components/common/Button/styled.ts
  src/components/hanowlApply/MainWebView/index.tsx
  src/components/hanowlApply/MainWebView/styled.ts
  src/components/hanowlApply/TeamsSkeleton/index.tsx
  src/components/hanowlApply/TeamsWebView/index.tsx
  src/components/hanowlApply/TeamsWebView/styled.ts
  src/components/hanowlApply/index.ts
  src/components/home/AlertBox/index.tsx
  src/components/home/TimeTableTab/index.tsx
  src/components/home/TimeTableTab/styled.ts
  src/constants/community/posts.ts
  src/constants/hanowlApply.ts
  src/screens/community/main/index.tsx
  src/screens/hanowlApply/applyContents/index.tsx
  src/screens/hanowlApply/confirm/index.tsx
  src/screens/hanowlApply/index.ts
  src/screens/hanowlApply/main/index.tsx
  src/screens/hanowlApply/selectTeam/index.tsx
  src/screens/home/index.tsx
  src/screens/main/index.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: ♻️ 리팩토링, ✨ 기능, 🎨 디자인, 🐛 버그
